### ISSUE TITLE
can anyone share the trained model file which is genralized on any type of image like mathpix

### ISSUE THREAD

**Issue by vyaslkv** [harvardnlp/im2markup#32]

**Comment by da03** [comment]
Hi, thanks for your interest in our code, but the short answer is that we don't have such models since we don't have access to such data.

The long answer is that end-to-end learning is usually not generalizable to data unseen at training time. Mathpix used our code but they have their own internal dataset which is not open to the public. According to our preliminary experiments, we need at least 10K training images to get a reasonable performance using our approach, so to train such a model we might need hundreds of thousands of images (with LaTeX) of various styles/fonts.

**Comment by vyaslkv** [comment]
Thanks for replying!! is there any way they could (mathpix) could release the dataset

**Comment by vyaslkv** [comment]
can I get your email id so that we could discuss regarding getting such data set because what I am thinking might solve this

**Comment by vyaslkv** [comment]
I can provide the dataset but I will need your little help to organize it and format it which is fine for training
