### ISSUE TITLE
why downsample by 2 in preprocess

### ISSUE THREAD

**Issue by StephenKyung** [harvardnlp/im2markup#45]
Hi, I'm trying to train this model in another mathematical expression real data.
while I doing that I have a question, Why you downsample images in preprocess_images.py ? can I change downsample_ration to 1.0 for better performance?
Thanks.

**Comment by da03** [comment]
Yes, my expectation is that no downsampling won't hurt performance (and could possibly increase performance). However, no downsampling means that images are larger than using downsampling, so it requires more GPU memory and might take longer per forward/backward pass since the feature maps are also larger.

We wanted to use a ratio as high as possible to make training faster. The reason we downsampled by 2 is that we looked at images in the dataset and tried different downsampling ratios, and using a ratio of 2 still enables humans to discern subscripts/superscripts, while using 4 makes some subscripts not discernable.

**Comment by StephenKyung** [comment]
Thanks!!
